spring:
  application:
    name: mapsintegration
  config:
    import: optional:classpath:config/platform-defaults.yml,optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    config:
      fail-fast: true
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids: true
olamaps:
  api:
    key: j6gXHJsn9rB5wABmU1l8pTbkhJkvv8rmu9gj4hdz
