spring:
  application:
    name: mapsintegration

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/food_delivery}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    show-sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

olamaps:
  api:
    base-url: https://api.olamaps.io
    key: ${OLA_MAPS_API_KEY:default_test_key}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
    instances:
      olaMapsRouting:
        baseConfig: default
